before_script:
  - docker build -t aske .
  
test_model_check:
  script:
    - docker run aske cabal v2-test :test-model-check

test_example_validity:
  script:
    - >
      docker run aske
      cabal exec deca --
      -m examples/askee/sir.askee
      --dbg-only-lex
    - >
      docker run aske
      cabal exec deca --
      -m examples/askee/sir.askee
      --dbg-only-parse
    - >
      docker run aske
      cabal exec deca --
      -m examples/askee/sir.askee
      --dbg-only-check
    - >
      docker run aske
      cabal exec deca --
      -m examples/askee/sir.askee
      --dbg-dump-cpp

test_example_simulation:
  script:
    - >
      docker run aske
      cabal exec deca --
      -m examples/askee/sir.askee
      --sim-ode=0:1:100