version: "3.9"

services:
  donu:
    build:
      context: .
      target: donu-execute
    volumes:
      - "./modelRepo:/build/modelRepo"

      # Uncomment to propagate local changes to the container for quicker
      # development:
      # - "./src:/build/src"
    ports:
      - "8000:8000"
    expose:
      - "localhost:8000:8000"
    networks:
      - donu-network
    environment:
      # This should be the same as the name of the service serving
      # AlgebraicJulia functionality
      ASKE_AJ_HOSTNAME: algebraic-julia

      # Hack: the default `Paths_aske_e.getDataDir` begins with `/root/.cabal/share`
      # when `cabal exec donu` is used as the execution command to run `donu`,
      # as it is in our Dockerfile. This directory doesn't exist at execution time 
      # in the container, for some reason.
      # This variable changes that prefix to `/build`, which is where we've
      # (manually, in the Dockerfile) COPY'd the files `donu` wants for execution, 
      # as listed in the cabal file's `extra-source-files` field.
      aske_e_datadir: /build

  algebraic-julia:
    build: ASKE-E-Simulation-WG/AlgebraicPetri-Stratification
    # TODO: leverage this mount when sending models between `donu` and AJ
    # volumes:
    #   - "./modelRepo:/models"
    expose:
      - "localhost:8001:8001"
    networks:
      - donu-network

  jupyter:
    build: jupyter
    ports: 
      - "8888:8888"
    networks:
      - donu-network
    environment:
      # This should be the same as the name of the service serving
      # donu functionality
      ASKE_DONU_HOSTNAME: donu

volumes:
  models:

networks:
  donu-network: