#!/bin/sh -e

HOST="aske.galois.com"
DEPLOY_USERNAME=${DEPLOY_USERNAME:-$USER}

USRHST="$DEPLOY_USERNAME@$HOST"

cabal build donu

DIR=/opt/donu/deploy
CERT_DIR=/opt/donu/cert
DONUARGS="--ssl-port=443 --ssl-cert=$CERT_DIR/cert.pem --ssl-key=$CERT_DIR/key.pem --ssl-address=0.0.0.0 --ssl-chain-cert=False"

# echo "Stopping server..."
# ssh $USRHST "umask 775; sg galwegians; killall -q donu; rm -rf $DIR; mkdir -p $DIR/log; exit"


DONU=`cabal exec -- which donu`
echo "Deploying..."
scp "$DONU" $USRHST:$DIR/donu
scp -r "modelRepo" $USRHST:$DIR

# echo "Starting server..."
# ssh $USRHST "umask 775; chgrp -r galwegians $DIR; sg galwegians; nohup $DIR/donu $DONUARGS > /dev/null" &
